# _config.yaml
title: Synker Helm chart repository
description: A chart repo for storing charts.
theme: jekyll-theme-hacker
url: "https://fazzani.synker.ovh/charts/"
repo_name: helm-repo

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore