charts:
  - name: openvpn
    repo:
      git: fazzani/charts
      published: http://fazzani.synker.ovh/openvpn/
  - name: traefik2
    repo:
      git: fazzani/charts
      published: http://fazzani.synker.ovh/traefik2/