replicaCount: 1

image:
  repository: linuxserver/openvpn-as
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

securityContext:
  capabilities:
    add:
      - NET_ADMIN
env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: Europe/Paris
  # - name: INTERFACE
  #   value: eth0
web:
  service:
    type: ClusterIP
    port: 8433
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: "openvpn.synker.ovh"
        paths:
        - /
service:
  type: ClusterIP
  dnsTcpPort: 9443
  dnsUdpPort: 1194

ingress:
  enabled: false

persistence:
  enabled: true
  # storageClass: default
  # existingClaim: nil
  storageClass: "nfs-client"
  accessModes: ReadWriteOnce
  size: 50Mi
  annotations: {}

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 2

